/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bl.Sender;
import javax.swing.JOptionPane;

/**
 *
 * @author Matthias
 */
public class RadioDialog extends javax.swing.JDialog {

    private boolean ok;
    private Sender radio;

    public boolean isOk() {
        return ok;
    }

    public Sender getRadio() {
        return radio;
    }
    
    
    /**
     * Creates new form RadioDialog
     */
    public RadioDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSendername = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        lbFrequenz = new javax.swing.JLabel();
        tfFrequenz = new javax.swing.JTextField();
        lbBand = new javax.swing.JLabel();
        tfBand = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        lbSendername.setText("Sendername");
        getContentPane().add(lbSendername);

        tfName.setText("Radio A1");
        getContentPane().add(tfName);

        lbFrequenz.setText("Frequenz");
        getContentPane().add(lbFrequenz);

        tfFrequenz.setText("194.6");
        getContentPane().add(tfFrequenz);

        lbBand.setText("Band:");
        getContentPane().add(lbBand);

        tfBand.setText("AM");
        getContentPane().add(tfBand);

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        getContentPane().add(btOk);

        btCancel.setText("Cancel");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if(!(tfBand.getText().equals("AM") || tfBand.getText().equals("FM"))){
            JOptionPane.showMessageDialog(this, "Bitte nur AM oder FM als Band eingeben.", "Fehler", JOptionPane.OK_OPTION);
        }
        else if(Double.parseDouble(tfFrequenz.getText()) <= 0 || Double.parseDouble(tfFrequenz.getText()) >= 1000){
            JOptionPane.showMessageDialog(this, "Bitte nur Werte > 0 und < 1000 als Frequenz eingeben.", "Fehler", JOptionPane.OK_OPTION);
        }
        else{
            radio = new Sender(tfName.getText(), Double.parseDouble(tfFrequenz.getText()), tfBand.getText());
        
            ok = true;
            this.dispose();
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        ok = false;
        this.dispose();
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RadioDialog dialog = new RadioDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btOk;
    private javax.swing.JLabel lbBand;
    private javax.swing.JLabel lbFrequenz;
    private javax.swing.JLabel lbSendername;
    private javax.swing.JTextField tfBand;
    private javax.swing.JTextField tfFrequenz;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
